[project]
name = "astrbot-plugin-spectrecore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astrbot>=3.5.23",
    "jsonpickle>=3.0.0",
]
